# Generated by Django 5.0.6 on 2024-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_publisher_books_publisher_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='books',
            field=models.ManyToManyField(related_name='publisher', related_query_name='publishers', to='pages.book'),
        ),
    ]
