# Generated by Django 5.0.6 on 2024-06-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_publisher_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(unique=True),
        ),
    ]
