# Generated by Django 5.0.6 on 2024-06-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_book_publication_date_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(related_name='category', related_query_name='categories', to='pages.book'),
        ),
    ]
